# .github/workflows/chromatic.yml

# ì›Œí¬ í”Œë¡œìš° ì´ë¦„
name: 'Chromatic ë°°í¬'

# ì›Œí¬ í”Œë¡œìš° ì´ë²¤íŠ¸
on: push

# ì‘ì—… ëª©ë¡
jobs:
  test:
    # ìš´ì˜ ì²´ì œ(OS)
    runs-on: ubuntu-latest
    # ì‘ì—… ë‹¨ê³„
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #ğŸ‘‡ ì›Œí¬ í”Œë¡œìš° ë‹¨ê³„ë¡œ Chromaticì„ ì¶”ê°€
      - uses: chromaui/action@v1
        # Chromatic GitHub ì‘ì—…ì— í•„ìš”í•œ ì˜µì…˜
        with:
          #ğŸ‘‡ Chromatic projectToken ì…ë ¥. ì°¸ê³  https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/
          projectToken: 274e5df260b3
          token: ${{ secrets.GITHUB_TOKEN }}
